### PR TITLE
Copyright Infringement

### PR DESCRIPTION
**Pull request by JeromSar**
@Mafrans
Hello,

It has come to my attention that this repository contains copyrighted material in violation of its provided license.
The material in question is released under the TotalFreedom General License (TFGL) [Version 1.0](https://github.com/TotalFreedom/License/blob/03bfff8a00006d46653661129004b534d6ebedc3/LICENSE.md) or [Version 2.0](https://github.com/TotalFreedom/License/blob/7e1a8d078b1c310b8ed618ce215ab77e2a7a099e/LICENSE.md) depending on the time infringing material was introduced to this repository.

Copyrighted material included in this repository violates its license due to one or more of the following:
* Redistributions of the material do not retain its copyright license in its exact form.
* The original authors of this software have been misrepresented or not reprepresented at all in one or more of the following locations:
  * _plugin.yml_ under `authors`
  * _README.md_
  * _TFM_Util.java_ under `DEVELOPERS`
* Redistributions of the material in question are available in non-source, object, packaged or compiled form.

In order to comply with the infringed material's license and its copyright restrictions, please either:
  a) Remove the copyrighted material from this repository; or
  b) Edit or adjust the required source files as necessary to comply with TFGL.
  
I hope to have properly and sufficiently informed you of the violations in this repository. If you have any further questions, don't hesitate to contact me.

Thanks in advance,
Jerom

### CODE REVIEW

**Comment by PacksGamingHD** [comment]
Could you explain instead of copy pasting something?

**Comment by PacksGamingHD** [comment]
Also may I ask how will adding a blank line in build.xml help?

**Comment by JeromSar** [comment]
@PacksGamingHD The description of this PR explains the copyright infringements. This repository does not allow the creation of issues, hence this is a PR. The blank line is a dummy edit.

**Comment by PacksGamingHD** [comment]
I don't see anything wrong and I don't see any JARS being distributed. Checked plugin and TFM_Utils and there is no readme.md

**Comment by JeromSar** [comment]
@PacksGamingHD Please read this PR's message.

**Comment by Mafrans** [comment]
I am sorry for the inconvenience, let me fix this ASAP

**Comment by JeromSar** [comment]
@Mafrans The issue is actually the missing copyright notice, not the missing readme. :)

**Comment by Mafrans** [comment]
well, then i will fix that too :)

**Comment by Mafrans** [comment]
i went through all listed files, maybe you could go fix it yourself @JeromSar because neither i or @PacksGamingHD can see anything wrong

**Comment by JeromSar** [comment]
@Mafrans As I said, the LICENSE.md notice is missing, and is required to be present without modifications on TFM based source.

**Comment by Mafrans** [comment]
Will fix

**Comment by Mafrans** [comment]
Fixed

**Comment by Mafrans** [comment]
Closed (i think)

**Comment by JeromSar** [comment]
@Mafrans The only problem now, is that the link isn't working.

**Comment by Mafrans** [comment]
DAMN YOU LINK D:

**Pull request merged**
